"""feat: teacher_training

Revision ID: 150e8699ecb8
Revises: 8b88cf26f30d
Create Date: 2025-10-19 15:33:24.335019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150e8699ecb8'
down_revision: Union[str, Sequence[str], None] = '8b88cf26f30d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('percent_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_1', sa.Float(), nullable=True),
    sa.Column('group_2', sa.Float(), nullable=True),
    sa.Column('group_3', sa.Float(), nullable=True),
    sa.Column('group_4', sa.Float(), nullable=True),
    sa.Column('group_5', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_percent_groups_id'), 'percent_groups', ['id'], unique=False)
    op.create_table('elementary_school',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('total_id', sa.BigInteger(), nullable=True),
    sa.Column('initial_years_id', sa.BigInteger(), nullable=True),
    sa.Column('final_years_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['final_years_id'], ['percent_groups.id'], ),
    sa.ForeignKeyConstraint(['initial_years_id'], ['percent_groups.id'], ),
    sa.ForeignKeyConstraint(['total_id'], ['percent_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elementary_school_id'), 'elementary_school', ['id'], unique=False)
    op.create_table('teach_stages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('early_education_id', sa.BigInteger(), nullable=True),
    sa.Column('elementary_school_id', sa.BigInteger(), nullable=True),
    sa.Column('middle_school_id', sa.BigInteger(), nullable=True),
    sa.Column('eja_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['early_education_id'], ['percent_groups.id'], ),
    sa.ForeignKeyConstraint(['eja_id'], ['percent_groups.id'], ),
    sa.ForeignKeyConstraint(['elementary_school_id'], ['elementary_school.id'], ),
    sa.ForeignKeyConstraint(['middle_school_id'], ['percent_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teach_stages_id'), 'teach_stages', ['id'], unique=False)
    op.create_table('teacher_training',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('teach_stages_id', sa.BigInteger(), nullable=True),
    sa.Column('adminitrative_dependencie', sa.String(length=255), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['teach_stages_id'], ['teach_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_training_id'), 'teacher_training', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_training_id'), table_name='teacher_training')
    op.drop_table('teacher_training')
    op.drop_index(op.f('ix_teach_stages_id'), table_name='teach_stages')
    op.drop_table('teach_stages')
    op.drop_index(op.f('ix_elementary_school_id'), table_name='elementary_school')
    op.drop_table('elementary_school')
    op.drop_index(op.f('ix_percent_groups_id'), table_name='percent_groups')
    op.drop_table('percent_groups')
    # ### end Alembic commands ###
