"""feat: alter table abscense add timestamp

Revision ID: 7f03cc5e8d0b
Revises: 9840dd7db698
Create Date: 2025-09-05 22:47:12.685616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f03cc5e8d0b'
down_revision: Union[str, Sequence[str], None] = '9840dd7db698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abscenses', sa.Column('timestamp', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abscenses', 'timestamp')
    # ### end Alembic commands ###
