"""feat: manage_complexity

Revision ID: 8b88cf26f30d
Revises: d6a714db705d
Create Date: 2025-10-19 15:17:46.340294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b88cf26f30d'
down_revision: Union[str, Sequence[str], None] = 'd6a714db705d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manage_complexity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('adminitrative_dependencie', sa.String(length=255), nullable=False),
    sa.Column('complexity_level', sa.String(length=255), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manage_complexity_id'), 'manage_complexity', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manage_complexity_id'), table_name='manage_complexity')
    op.drop_table('manage_complexity')
    # ### end Alembic commands ###
