"""feat: teacher_regularity

Revision ID: d6a714db705d
Revises: 56181b7ab130
Create Date: 2025-10-19 15:01:55.308774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a714db705d'
down_revision: Union[str, Sequence[str], None] = '56181b7ab130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_regularity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('adminitrative_dependencie', sa.String(length=255), nullable=False),
    sa.Column('average_regularity', sa.Float(), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_regularity_id'), 'teacher_regularity', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_regularity_id'), table_name='teacher_regularity')
    op.drop_table('teacher_regularity')
    # ### end Alembic commands ###
